#!/bin/sh
cp -u $HOME/.gittmp/hooks/* .git/hooks/

set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT

# Tell ctags to go through all the git ls-files
git ls-files -cd | ctags -L - -f .git/tags.$$

mv .git/tags.$$ .git/tags
