#!/bin/sh
cp -u $HOME/.gittmp/hooks/* .git/hooks/

set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT

function ggeneric {
	git ls-files -cd | ctags -L - -f .git/tags.$$
}

function gelixir {
	ctags -R -f .git/tags.$$
}

function gruby {
	git ls-files -cd | ctags -L - -f .git/tags.$$
	bundle show --paths | ctags -L - -af .git/tags.$$
}

# Tell ctags to go through all the git ls-files
case "$1" in
	"ruby")		gruby ;;
	"elixir")	gelixir ;;
	*)			ggeneric ;;
esac

mv .git/tags.$$ .git/tags
