#!/bin/bash

cd $HOME/anime/ ;

anime=$(ls *.mkv | tr "_" " " | rev | cut -d"-" -f2- | rev | uniq > list.tmp)

while read -r line; do
    mkdir "$line" 2> /dev/null
    mv "$line"*.mkv "$line/"
done < list.tmp

rm list.tmp
