#!/bin/bash
ping -c 1 -t 1 10.1.1.7;
if [ $? -eq 0 ]; then
    if ps aux | grep "[r]sync" > /dev/null
    then
        echo "running process"
    else
        rsync -P -avrz --ignore-existing --remove-source-files \
        /home/kyle/downloads/rtorrent/completed/* 10.1.1.7:/home/kyle/anime/Queued/ && ssh \
        10.1.1.7 '~/bin/anime-sort'
    fi
fi
