#!/bin/bash

REMOTE_HOST=192.168.20.10

ping -c 1 -t 1 $REMOTE_HOST;
if [ $? -eq 0 ]; then
    if ps aux | grep "[r]sync" > /dev/null
    then
        echo "running process"
    else
        rsync -P -avrz --ignore-existing --remove-source-files \
        /home/kyle/downloads/rtorrent/completed/ $REMOTE_HOST:/home/kyle/anime/ && \
        ssh $REMOTE_HOST '~/.bin/anime-sort'
    fi
fi
