#!/bin/bash

# External IP Finder and Emailer

#ExternalIp=`dig +short myip.opendns.com @resolver1.opendns.com`

#while read -r line
#do
#    if [[ "$ExternalIp" != $line ]]; then
        # Are Not the same, send an email and update the file
#        read -r -d '' email <<EOF
#To: email@kylescottmcgill.com
#From: `hostname`@kylescottmcgill.com
#Subject: External IP Address
#
#IP Address: $ExternalIp
#EOF
#        echo "$email" | msmtp -a default email@kylescottmcgill.com
#        : > .ip
#        echo "$ExternalIp" > $HOME/.ip
#    fi
#done < "$HOME/.ip"
