#!/bin/sh

case "$(xrandr -q | grep -w "connected" | wc -l)" in
	"1") xrandr --output HDMI1 --off --output DP1 --off --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal && $HOME/.config/bspwm/bspwmrc ;;
	"2") xrandr --output HDMI1 --mode 2560x1080 --pos 1920x0 --rotate normal --output DP1 --off --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal && $HOME/.config/bspwm/bspwmrc ;;
esac

