#!/bin/sh

# TODO:
# Set up Work Screens as well
# Use FN Screen Keys to do the transisition

function common {
    # Disable Beep
    xset -b ;
    # Disable Mouse Acceleration
    xset m 1/1 0

    # Set Wallpaper Again
    sh $HOME/.fehbg

    # Run bspwm config to reconfigure
    $HOME/.config/bspwm/bspwmrc
}

case "$(xrandr -q | grep -w "connected" | wc -l)" in
	"1") xrandr --output HDMI1 --off --output DP1 --off --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal && $HOME/.config/bspwm/bspwmrc && common ;;
	"2") xrandr --output HDMI1 --off --output DP1 --off --output eDP1 --off && xrandr --output HDMI1 --mode 2560x1080 --pos 1920x0 --rotate normal --output DP1 --off --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal && $HOME/.config/bspwm/bspwmrc && common ;;
esac

