#!/bin/bash

cd ~/Music/youtube/ && youtube-dl https://www.youtube.com/playlist?list=PLiFU_tw8Vf8yFEp7Pjgul8--6XnKYYLnd --extract-audio --audio-format=mp3 ;
cd ~/Music/monstercat/ && youtube-dl https://soundcloud.com/monstercat/ --extract-audio --audio-format=mp3 ;
cd ~/Music/eden/ && youtube-dl https://soundcloud.com/eden-mcmxcv/tracks --extract-audio --audio-format=mp3 ;
cd ~/Music/soundcloud/ && youtube-dl https://soundcloud.com/kylescottmcgill/sets/work --extract-audio --audio-format=mp3 ;
echo -e "please update mpd";
