#!/bin/sh
# mix of inspiration from z3bra and my own shit

temp() {
    awk '{print $1/1000}' /sys/class/thermal/thermal_zone0/temp 
}
mem() {
    free -m | awk 'NR==2 {print $3}' 
}
clock() {
    date +'%e %b %R'
}
batt() {
    cat /sys/class/power_supply/BAT0/capacity 2>/dev/null
}
music() {
    mpc current
}
vol() {
    amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/' | sed -e 's/%//g'
}
tags() {
    SPACE_NUM=$(bspc query -D -d);
    case "$SPACE_NUM" in
	"I")
	    WORKSPACE="■ □ □ □ □";;
	"II")
	    WORKSPACE="□ ■ □ □ □";;
	"III")
	    WORKSPACE="□ □ ■ □ □";;
	"IV")
	    WORKSPACE="□ □ □ ■ □";;
	"V")
	    WORKSPACE="□ □ □ □ ■";;
    esac
    echo -n $WORKSPACE
}

# Fill buffer, output it to stdout.
while :; do
    buf="%{l} %{B#FFeeeeee} "
    buf="${buf} %{F#FFa69c8e} batt "
    buf="${buf} %{F#FF1d1f21} $(batt) "
    buf="${buf} %{F#FFa69c8e} mem "
    buf="${buf} %{F#FF1d1f21} $(mem) "
    buf="${buf} %{F#FFa69c8e} vol "
    buf="${buf} %{F#FF1d1f21} $(vol) %{c}"
    buf="${buf} %{F#FF120f20} $(music) %{r}"
    buf="${buf} %{F#FFFFFFFF} $() "
    buf="${buf} %{F#FFFFFFFF} $() "   
    buf="${buf} %{F#FFFFFFFF} $() "   
    buf="${buf} %{F#FFFFFFFF} $() "   
    buf="${buf} %{F#FF1d1f21} $(clock) "
    buf="${buf} %{F#FFFFFFFF} $() "
    buf="${buf} %{F#FFFFFFFF} $() "
    buf="${buf} %{F#FFFFFFFF} $() "

    echo $buf
    sleep 1 
done
