#!/bin/bash

echo -e " :: Starting to Sync Home"

cd ~

rsync -aAXcP /home/kyle/ /mnt/usb/kyle/ \
    --exclude={.adobe,.bash_history,build/*,.bundler,.cache,.codeintel,.composer,.drirc,.esd_auth,.gem,.gnupg,.httpie,.ICEauthority,.lesshst,.local,mail/*,music/*,.mysql_history,.npm,.nvm,.offlineimap,pictures/*,.pki,.pulse-cookie,.rubies,.Skype,.w3m,.Xauthority,misc,downloads/*,.gnome,.gstreamer-0.10,.macromedia,.mozilla,.steam,.steampath,.steampid,.thumbnails,.umit,.weechat,amv,anime};

# cp -rvfu /mnt/usb/kyle /home/

echo -e " :: Finished Syncing"

