#!/usr/bin/env sh

#: "${wm:=monsterwm}"
#: "${ff:="/tmp/${wm}.fifo"}"
#[ -p "$ff" ] || mkfifo -m 600 "$ff"

# spawn a statusbar
#while read -t 22 -r line || true; do
#    echo "$line" | grep -qEx "(([[:digit:]]+:){4,6}[[:digit:]]+ ?)+" && prev="$line" || line=
#    statusinfo ${line:-$prev}
#done < "$ff" | bar &

#"$wm" > "$ff"

ff="/tmp/monsterwm.fifo"
[[ -p $ff ]] || mkfifo -m 600 "$ff"

# desktop names
ds=("web" "dev" "foo" "null" "1" "2" "3" "4" "5")

# layout names
ms=("T" "M" "B" "G" "F")

while read -t 60 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        read -ra desktops <<< "$wmout" && unset r
        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"
            ((c)) && fg="\\f4" i="${ms[$m]}" || fg="\\f3"
            ((u)) && w+='\f5!'
            r+="$fg${ds[$d]} ${w/#0/\\f8-} \\f3:: "
        done
        r="${r%::*}"
    fi
    printf "\\\l%s\\\r%s\n" "$r\\f5[\\f3$i\\f5]" "$(date +"%F %R")"
done < "$ff" | bar &

# pass output to fifo
monsterwm > "$ff"
