#!/bin/bash

function DesktopSetup {
    i=1
    for monitor in $(bspc query -M); do
	bspc monitor $monitor -n "$i" -d {I,II,III,IV,V,VI,VII,VIII,IX}
	let i++
    done
    NMON=$i
    unset i
}

case "$(hostname)" in
    "ouroboros") 
        bspc desktop -n 1
        bspc monitor -d 1 2 3 4 5 6 7 8 9
        ;;
    "turtil") 
	DesktopSetup
        ;;
    "xm-dev") 
	bspc monitor DVI-D-0 -d I II III && \
	bspc monitor HDMI-0 -d IV && \
	bspc monitor DVI-D-1 -d V
	;;
    *) 
        bspc desktop -n 1
        bspc monitor -d 1 2 3 4 5 6 7 8 9
        ;;
esac


bspc config border_width        1
bspc config window_gap          10

bspc config top_padding 20
bspc config bottom_padding 20
bspc config right_padding 20
bspc config left_padding 20

# Visual options
bspc config split_ratio         0.75
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config focus_follows_focus true
bspc config history_aware_focus true
bspc config apply_floating_atom true
bspc config ignore_ewmh_focus true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_locked_border_color   "#708D8F"
bspc config active_locked_border_color   "#808C8D"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a URxvt pseudo_tiled=off border=off
bspc rule -a Chromium border=off desktop=V
bspc rule -a Firefox border=off fullscreen=on
bspc rule -a Steam floating=on
bspc rule -a Gvim border=off
bspc rule -a feh floating=on manage=on
bspc rule -a mpv floating=on follow=on

export BSPWM_SOCKET="/tmp/bspwm-socket"
export PANEL_FIFO="/tmp/panel-fifo"

#~/.config/bspwm/panel/panel &
