#!/bin/bash

function DesktopSetup {
i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor -n "$i" -d {1,2,3,4,5,6,7,8}
	let i++
done
NMON=$i
unset i
}

case "$(hostname)" in
	"turtil")
		DesktopSetup
		;;
	*)
		bspc desktop -n 1
		bspc monitor -d 1 2 3 4 5
		;;
esac

bspc config border_width 1
bspc config window_gap 10

bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

# Visual options
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config auto_alternate false
bspc config auto_cancel true
bspc config focus_follows_focus false
bspc config history_aware_focus false
bspc config apply_floating_atom true
bspc config ignore_ewmh_focus true
bspc config normal_border_color "#151B22"
bspc config active_border_color "#151B22"
bspc config focused_border_color "#151B22"
bspc config presel_border_color "#7394BB"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_locked_border_color "#708D8F"
bspc config active_locked_border_color "#808C8D"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r $(bspc rule -l | awk '{print $1}')
bspc rule -a Skype pseudo_tiled=off border=off split_ratio=0.75
bspc rule -a Steam floating=on border=off center=on
bspc rule -a Chromium border=off center=on
bspc rule -a mpv floating=on follow=on center=on border=off
bspc rule -a Termite border=on follow=on split_ratio=0.75
bspc rule -a jetbrains-idea border=off floating=on follow=off
bspc rule -a DBeaver border=off follow=off

export BSPWM_SOCKET="/tmp/bspwm-socket"
export PANEL_FIFO="/tmp/panel-fifo"

