#!/bin/bash

function DesktopSetup {
i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor -n "$i" -d {1,2,3,4,5,6,7,8}
	let i++
done
NMON=$i
unset i
}

DesktopSetup

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width 1
desktop_config window_gap 25

bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

# Visual options
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false

bspc config remove_unplugged_monitors true
bspc config ignore_ewmh_focus true

bspc config normal_border_color "#222222"
bspc config active_border_color "#222222"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#CF4C56"

# Rules
bspc rule -a Chromium border=off center=on
bspc rule -a mpv floating=on follow=on center=on border=off
bspc rule -a URxvt border=on follow=on split_ratio=0.5
bspc rule -a jetbrains-idea border=off floating=on follow=off center=on
bspc rule -a DBeaver border=off follow=off

#$HOME/bin/monitor
#$HOME/bin/mouse
#sxhkd & # Need to write a wrapper to kill if already running etc
